Server:
  port: 8080

spring:
  application:
    name: elasticsearch-demo
  data:
    elasticsearch:
        cluster-name: es-sea-cluster
        cluster-nodes: 192.168.1.207:9300, 192.168.1.207:9301, 192.168.1.207:9302
